<?php

return [
    'per_page' => 4,
    'flash_auto_hide_ms' => 3000,

    'postcode_pattern' => '/^[1-9][0-9]{3}[A-Z]{2}$/',
    'straatnaam_pattern' => '/^(?:[1-9]\d*e\s+)?[A-Za-zÀ-ÿ\'][A-Za-zÀ-ÿ\s\'\-\.]{1,147}$/u',

    'straat_suffixes' => [
        'straat',
        'steeg',
        'laan',
        'weg',
        'gracht',
        'singel',
        'plein',
        'pad',
        'dreef',
        'boulevard',
        'park',
        'ring',
        'dijk',
        'kade',
        'hof',
        'veld',
        'akker',
        'dam',
        'wal',
        'haven',
        'markt',
        'sluis',
        'poort',
        'buurt',
        'gaard',
        'tuin',
        'brug',
        'baan',
        'zoom',
        'wetering',
        'plantsoen',
    ],
    'plaats_pattern' => '/^[A-Za-zÀ-ÿ][A-Za-zÀ-ÿ\s\'\-\.]{1,98}$/u',
    'huisnummer_pattern' => '/^\d{1,5}[a-zA-Z]{0,2}$/',
    'mobiel_pattern' => '/^(06[\s\-]?(\d[\s\-]?){8}|\+31[\s\-]?6[\s\-]?(\d[\s\-]?){8})$/',

    'blocked_address_words' => [
        'israel',
        'israël',
        'palestina',
        'palestine',
        'duitsland',
        'germany',
        'frankrijk',
        'france',
        'belgie',
        'belgië',
        'belgium',
        'amerika',
        'america',
        'engeland',
        'england',
    ],

    'dutch_plaatsen' => [
        'Aalsmeer',
        'Alkmaar',
        'Almere',
        'Amersfoort',
        'Amsterdam',
        'Apeldoorn',
        'Arnhem',
        'Breda',
        'Delft',
        'Den Bosch',
        'Den Haag',
        'Deventer',
        'Dordrecht',
        'Eindhoven',
        'Enschede',
        'Groningen',
        'Haarlem',
        'Heerlen',
        'Hilversum',
        'Hoofddorp',
        'Leeuwarden',
        'Leiden',
        'Maastricht',
        'Nijmegen',
        'Rotterdam',
        'Tilburg',
        'Utrecht',
        'Venlo',
        'Zaanstad',
        'Zoetermeer',
        'Zwolle',
        "'s-Hertogenbosch",
        "'s-Gravenhage",
    ],

    'medewerker_min_age' => 15,
    'medewerker_max_age' => 100,
];
